[build]
target = "x86_64-unknown-none"
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "panic=abort",
    "-C", "target-feature=+aes,+avx,+bmi1,+f16c,+lzcnt,+movbe,+pclmulqdq,+popcnt,+sse,+sse2,+sse3,+ssse3,+sse4a,+sse4.1,+sse4.2,+xsave,+xsaveopt"
]
